### ISSUE TITLE
Ti.Draggable Not Supported by TitaniumSDK 5.0.0.GA

### ISSUE THREAD

**Issue by RayKahn** [animecyc/TiDraggable#31]
I copied the zip file to the root of my project but I am now getting this exception:

[ERROR] :  Script Error Couldn't find module: ti.draggable for architecture: x86_64

Is there a 64 bit version?

Hi there,
Any plans for a compatible version?

WARN] :   Could not find a valid Titanium module id=ti.draggable version=2.0.0 platform=ios,iphone,commonjs deploy-type=development
[ERROR] :  Could not find all required Titanium Modules:
[ERROR] :     id: ti.draggable   version: 2.0.0  platform: ios,iphone,commonjs   deploy-type: development
TRACE  | titanium exited with exit code 1
ERROR  | Error: ti run exited with error code 1
    at ChildProcess.<anonymous> (/Users/raykahn/.appcelerator/install/5.0.1/package/node_modules/appc-cli-titanium/plugins/run.js:89:66)
    at ChildProcess.EventEmitter.emit (events.js:117:20)
    at Process.ChildProcess._handle.onexit (child_process.js:789:12)

**Comment by designbymind** [comment]
Hi @RayKahn,

Just wanted to let you know that I am successfully using TiDraggable with the 5.0.0 SDK. Works like a charm 🍀(an Alloy version would be radical!) 

· Download the module and unzip it
- Open up the unzipped directory: TiDraggable-master/ios
- Drag build.py into terminal on OS X (this will build the module and produce another zip file called "ti.draggable-iphone-2.0.4.zip" within the same directory)
- Unzip the above which will produce a directory name "modules" within the same directory as above (TiDraggable-master/ios)
- Copy the directory contents (only ti.draggable) of of the newly unzipped
- Paste ti.draggable in the correct directory for native modules (in your case iOS), see below:
  **/Library/Application Support/Titanium/modules/iphone/**_ti.draggable_
- After that, ensure you update/save your tiapp.xml file to include the newly added module into your project:
  <code>
  &lt;modules&gt;
  &lt;module platform="iphone"&gt;ti.draggable&lt;/module&gt;
  &lt;/modules&gt;
  </code>
- Clean your project build in Appcelerator Studio: **Project > Clean >** _YOUR_PROJECT_
- You should then include this module in the controller desired:
  - **var Draggable = require('ti.draggable');**

That should expose the TiDraggable options/methods to your project & you'll be ready to rock n' roll 😎
- Per usual, check out the example file if needed: https://github.com/animecyc/TiDraggable/blob/master/ios/example/app.js

Hope that helps you!

· Jason

**Comment by RayKahn** [comment]
Thanks for your help... I did get the to work.

**Comment by Fenil15** [comment]
@RayKahn @designbymind  - I am unable to build it. Getting errors while building. Can you upload it with 64 bit support?

**Comment by designbymind** [comment]
Hi @Fenil15,

Are you getting an error/exception returned during the build process? If so, can you please share?

Since both @RayKahn & I are able to successfully build for SDK 5.0.0 from the latest dist, I'm fairly sure that re-uploading the module will not be the solution to your problem...

Just for the heck of it, below is my current environment:
· Ti.Draggable 2.0.0
· iOS 9.1
· Appcelerator Studio 4.3.3
· Titanium SDK 5.0.2.GA
· iPhone 5s (simulator) / iPhone 6s (device/simulator) / iPhone 6s Plus (device)

**Comment by RayKahn** [comment]
No resolved.

**Comment by Fenil15** [comment]
@RayKahn Check it out this link - Got it working for me https://github.com/caspahouzer/TiDraggable/blob/master/ios/dist/ti.draggable-iphone-2.1.2.zip
