### ISSUE TITLE
Seems like it needs to be recompiled for SDK 6.0.0

### ISSUE THREAD

**Issue by annakozy2011** [animecyc/TiDraggable#43]
I only have this module in the app, and it crashes with this error: 

[INFO] :   MultiDex: VM has multidex support, MultiDex support library is disabled.
[WARN] :   V8Object: (main) [260,282] Runtime disposed, cannot set property 'userAgent'
[DEBUG] :  AndroidRuntime: Shutting down VM
[ERROR] :  TiApplication: (main) [27,309] Sending event: exception on thread: main msg:java.lang.UnsatisfiedLinkError: dlopen failed: library "libstlport_shared.so" not found; Titanium 6.0.0,2016/11/13 01:23,undefined
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: library "libstlport_shared.so" not found
[ERROR] :  TiApplication: 	at java.lang.Runtime.loadLibrary(Runtime.java:372)
[ERROR] :  TiApplication: 	at java.lang.System.loadLibrary(System.java:1076)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:151)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:118)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
[ERROR] :  TiApplication: 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
[ERROR] :  TiApplication: 	at com.bouncingfish.pronamel.GwcApplication.onCreate(GwcApplication.java:46)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:148)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[INFO] :   art: Starting a blocking GC HeapTrim

**Comment by yozef** [comment]
+1

**Comment by yozef** [comment]
[ti.draggable-android-2.1.4.zip](https://github.com/animecyc/TiDraggable/files/735989/ti.draggable-android-2.1.4.zip)
